### ISSUE TITLE
 Empty Response as a crash From Step Builder(SKL16.XL.03.01.04.T1)

### ISSUE THREAD

**Issue by gautambishwas** [Compro-Single-Step/SIMS-Builder#102]
Getting crash message when trying to preview task

**Failed to load resource: net::ERR_EMPTY_RESPONSE**

**Comment by dhirendra-singh81** [comment]
@gautambishwas, please add the exact replication steps.

@tushar-compro, please add a timeline for this issue

**Comment by gautambishwas** [comment]
As Discussed with Tushar Pull Request is already Generated for this issue.

**Comment by tushar-compro** [comment]
Issue resolved
