### ISSUE TITLE
Cached data

### ISSUE THREAD

**Issue by gautambishwas** [Compro-Single-Step/SIMS-Builder#104]
If we uploading the document data multiple time SIM Builder(Tabs of Worksheet Images)  are not accepted modified data.

Issue is valid for all task

**Comment by prateekbhutani** [comment]
Pull Request:
"https://github.com/Compro-Single-Step/SIMS-Builder/pull/126/files"

**Comment by dhirendra-singh81** [comment]
@prateekbhutani, is this done from your side? Shall I review the pull request?

**Comment by prateekbhutani** [comment]
The issue reported is fixed in Pull Request : 
"https://github.com/Compro-Single-Step/SIMS-Builder/pull/126/files"

However, there are some other related issue which remain.
