### ISSUE TITLE
Glyphicons and fa icons not visible

### ISSUE THREAD

**Issue by aman-compro** [Compro-Single-Step/SIMS-Builder#13]
![2017-03-09_10-34-35](https://cloud.githubusercontent.com/assets/25973788/23736753/265751da-04b4-11e7-9932-172fe3a58876.jpg)

The icons appear when i use bootstrap CDN in index.html

**Comment by chirag-compro** [comment]
Bootstrap 4 node module package doesnot contain glyphicons. This could be one of the reason for this. We can solve this issue using some other library for the icons.

**Comment by aman-compro** [comment]
Issue Found Fixed.
