### ISSUE TITLE
Crash Message into console error(SKL16.XL.03.01.04.T1)

### ISSUE THREAD

**Issue by gautambishwas** [Compro-Single-Step/SIMS-Builder#135]
Replication step:

-  Upload the Document Data in in step 1( please take resource from attached file)
-  Upload Worksheet Images and Preview Images
-  Click on preview button (FYI SIMplayer not working means step is not generated correctly)
-  Refresh the page 
-  After refreshing, you will get the crash message in console check attached image
-  Now you are not able to remove worksheet Images.

![upload](https://cloud.githubusercontent.com/assets/25953604/25083921/7bbfe2a4-2377-11e7-8d9e-3f6cca3e6211.png)
![crashmessage](https://cloud.githubusercontent.com/assets/25953604/25083922/7bc90fc8-2377-11e7-8d36-10de3effe6b2.png)

I am using below resource to generate task
[test.zip](https://github.com/Compro-Single-Step/SIMS-Builder/files/925299/test.zip)

**Comment by tushar-compro** [comment]
Resolved
