### ISSUE TITLE
Handle to insert XML node dynamically (based on a condition)

### ISSUE THREAD

**Issue by chirag-compro** [Compro-Single-Step/SIMS-Builder#150]
A handle needs to be provided to include/exclude an XML node based on the input from the user.
![insertnodedynamically](https://cloud.githubusercontent.com/assets/25973301/25375222/a34e4ecc-29bd-11e7-86bf-eb95b3bafdc4.png)

**Comment by tushar-compro** [comment]
Issue resolved using handlebar functionality.
