### ISSUE TITLE
target attribute set attribute is lost during translation

### ISSUE THREAD

**Issue by aman-compro** [Compro-Single-Step/SIMS-Builder#157]
**<event id="9998" followup="1" target-attribute-set="Cancelbutton" desc="Sum Function Argument Dlg: Cancel clicked"/>** 

in skill XML gets converted into 

**<event id="9998" desc="Sum Function Argument Dlg: Cancel clicked" followup="1"/>**

**Comment by tushar-compro** [comment]
Issue resolved.
Code merged in develop.
