### ISSUE TITLE
Tab Page Component as wrapper of Dynamically generated dropzones.

### ISSUE THREAD

**Issue by prateekbhutani** [Compro-Single-Step/SIMS-Builder#174]
Use Case: When an HTML file is dropped in a dropzone, I need to dynamically generate a set of dropzones corresponding to the number of Image Tags present in the HTML File. When HTML file is dropped it will be read and Model will be updated accordingly using a Front end translator function.

Issue: UIConfig is unable to generate a Dropzone wrapped inside TabPage component dynamically. This needs an update to the Tab Page component so that it generates the children dropzones from the UIConfig and iterates them based on Data Model.

Please checkout branch "InsertPictureSkill" to replicate the issue.

**Comment by ashish-compro** [comment]
need to be discussed with Babanpreet and Dhirendra.

**Comment by ashish-compro** [comment]
Fixed by providing support of adding multiple files in a dropzone.
